name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: python -m pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Check poetry.lock
        run: poetry lock --check

      # - name: pyright
      #   run: poetry run pyright .

      - name: ruff-format
        run: poetry run ruff format --check .

      - name: ruff
        run: poetry run ruff check --output-format github .
