name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qgis_image_tag: [release-3_28]
    env:
      OS: ubuntu
      QGIS_IMAGE_TAG: ${{ matrix.qgis_image_tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Pull QGIS image
        run: docker pull qgis/qgis:${{ matrix.qgis_image_tag }}

      - name: Export requirements.txt
        run: |
          pip3 install poetry
          poetry export --with dev -f requirements.txt -o requirements.txt

      - name: Run tests
        run: >
          docker run --rm --volume `pwd`:/app -w=/app qgis/qgis:${{ matrix.qgis_image_tag }} sh -c "
            pip3 install -r requirements.txt &&
            PYTHONPATH=/app xvfb-run -s '+extension GLX -screen 0 1024x768x24' pytest -v --cov --cov-report=xml --cov-report=term
          "

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,QGIS_IMAGE_TAG
          fail_ci_if_error: false
